-- create database 
CREATE DATABASE STUDENT1;
USE STUDENT1;

-- CREATE TABLE
CREATE TABLE EMPLOYEES (
	EMPID INT,
    EMPNAME VARCHAR(30),
    DEPARTMENT VARCHAR(40),
    SALARY INT,
    AGE INT,
    GENDER VARCHAR(40)
);


SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES
VALUES
(1,"RAKESH","CSE",10000,20,"MALE"),
(2,"SINDHU","ECE",30000,21,"FEMALE"),
(3,"NEHA","ECE",20000,22,"FEMALE"),
(4,"USHA","IT",34000,24,"FEMALE"),
(5,"SRINU","CSE",10000,20,"MALE"),
(6,"KOLLA","ECE",4000,30,"MALE"),
(7,"BALAJI","CSE",2000,27,"MALE"),
(8,"RAVI","ECE",36000,26,"MALE"),
(9,"RAKESH2","CSE",100000,30,"MALE"),
(2,"VIJAY","ECE",35000,29,"MALE");

SELECT * FROM EMPLOYEES;

-- TOTAL NO OF EMPLOYEES
SELECT COUNT(*) AS total_employees FROM employees;


-- TOTAL SALARY TO ALL EMPLOYEES
SELECT SUM(salary) AS total_salary FROM employees;

-- AVERAGE  SALARY 
SELECT AVG(salary) AS average_salary FROM employees;

-- highest salary 
SELECT max(salary) AS highestl_salary FROM employees;

-- lowest salary
SELECT min(salary) AS lowest_salary FROM employees;

-- NO OF DEPARTMENTS IN CSE
SELECT SUM(salary) AS CSE_total_salary
FROM employees
WHERE department = 'CSE';

-- AVAERAGE AGE OF EMPLOYEES
SELECT AVG(AGE) AS AVERAGE_AGE
FROM employees;

-- HIGHEST AND LOWEST SALARY 

SELECT 
    MAX(salary) AS highest_salary,
    MIN(salary) AS lowest_salary
FROM employees;


-- NO OF EMPLOYEES IN THE DEPT
SELECT DEPARTMENT,COUNT(*) AS EMPLOYEE_COUNT 
FROM EMPLOYEES 
GROUP BY DEPARTMENT;

-- TOTAL SALARY OF EACH DEPARTMENT
SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- DISPLAY EACH DEPARTMENTS 
SELECT
	DEPARTMENT,
	COUNT(*) AS EMPLOYEE_COUNT,
	SUM(SALARY) AS TOTAL_SALARY,
	AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- DISPLAY EACH DEPARTMENT 
SELECT 
	DEPARTMENT,
    COUNT(*) AS TOTAL_COUNT,
    SUM(SALARY) AS TOTAL_SALARY,
    AVG(SALARY) AS AVERAGE_SALARY,
    MAX(SALARY) AS MAXIMUM_SALARY,
    MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- DISPLAY ONLY DEPARTMENT AVERAGE SALARY GREATER THAN 50000

SELECT 
    DEPARTMENT,
    AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 50000;


-- DISPLAY DEPARTMENT MORE THAN 3 EMPLOYEES
SELECT 
    DEPARTMENT,
    COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) > 3;

-- COUNT NO OF DIST DEPARTMENTS
SELECT COUNT(DISTINCT DEPARTMENT) AS DISTINCT_DEPARTMENTS
FROM EMPLOYEES;

-- TOTAL SALARY OF EMPLOYEES GREATER THAN 40000
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE SALARY > 40000;

-- DISPLAY THE DEPARTMENT WITH THE HIGHEST TOTAL SALARY
 SELECT 
    DEPARTMENT,
    SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY TOTAL_SALARY DESC
LIMIT 1;
