-- create database
create database trip_analaysis;
use trip_analaysis;

desc tips;
-- CHANGE COLUMN NAME SEX TO GENDER
alter table tips rename column sex to gender;

-- 1. selecting table data
select * from tips;

-- 2.select totalbill,gender
select total_bill,gender from tips;

---- 3. FIND THE NON-SMOKER PEOPLE
SELECT * FROM TIPS WHERE SMOKER = 'NO';

-- 4. FIND THE DINNER TIME RECORDS
SELECT * FROM TIPS WHERE TIME = 'DINNER';

-- 5. FIND NON SMOKER DINNER TIME RECORDS
SELECT * FROM TIPS WHERE SMOKER = 'NO' AND TIME = 'DINNER';

-- 6. FIND THE PEOPLE WHOSE TIP IS GREATER THAN 2
SELECT * FROM TIPS WHERE TIP > 2;

-- 7. FIND THE RECORDS WHOSE TOTAL BILL IN BETWEEN 10 TO 25
SELECT * FROM TIPS WHERE TOTAL_BILL BETWEEN 10 AND 25;

-- 8. FIND THE FEMALE SMOKER PEOPKE
SELECT * FROM TIPS WHERE GENDER = 'FEMALE' AND SMOKER = 'YES';

-- 9. FIND THE RECORDS EITHER SAT, SUN, OR MON RECORDS
SELECT * FROM TIPS WHERE DAY = 'SUN' OR DAY = 'MON' OR DAY = 'SAT';
SELECT * FROM TIPS WHERE DAY = 'MON';

-- 10. FIND THE ALL RECORDS WHOSE SIZE IS 2,3,4
SELECT * FROM TIPS WHERE SIZE IN (2,3,4);

-- 11. FIND THE TOTAL RECORDS
SELECT COUNT(*) FROM TIPS;

-- 12. FIND THE LADIES RECORDS COUNT
SELECT GENDER,COUNT(*) FROM TIPS WHERE GENDER = 'FEMALE';
SELECT GENDER FROM TIPS WHERE GENDER = 'FEMALE';
-- SELECT TOTAL_BILL,COUNT(*) FROM TIPS WHERE GENDER = 'FEMALE';    RAISES ERROR

-- 13. FIND THE MALE SMOKER COUNT
SELECT COUNT(*) FROM TIPS WHERE GENDER = 'MALE' AND SMOKER = 'YES';
SELECT GENDER,SMOKER,COUNT(*) FROM TIPS WHERE GENDER = 'MALE' AND SMOKER = 'YES';

-- 14. FIND THE TOTAL BILL OF DINNER TIME
SELECT SUM(TOTAL_BILL) FROM TIPS WHERE TIME = 'DINNER' OR TIME = 'LUNCH';

-- 15. FIND THE MINIMUM TIP AND MAXIMUM TIP
SELECT MIN(TIP),MAX(TIP) FROM TIPS;

SELECT COUNT(*) FROM TIPS WHERE SIZE = 2;
SELECT COUNT(*) FROM TIPS WHERE SIZE = 3;
SELECT SIZE,COUNT(*) FROM TIPS GROUP BY SIZE;

SELECT SUM(TOTAL_BILL) FROM TIPS WHERE TIME = 'DINNER';
SELECT SUM(TOTAL_BILL) FROM TIPS WHERE TIME = 'DINNER';
SELECT TIME,SUM(TOTAL_BILL) FROM TIPS GROUP BY TIME;

-- FIND THE PEOPLE COUNT AS PER THE GENDER
SELECT GENDER,COUNT(*) FROM TIPS GROUP BY GENDER;

-- FIND THE FEMALE COUNT AS PER THE SMOKER
SELECT GENDER,SMOKER,COUNT(*) FROM TIPS WHERE GENDER = 'FEMALE' GROUP BY SMOKER;

-- FIND THE AVG TOTAL BILL FOR SIZE 2,3 AND 4
SELECT SIZE,AVG(TOTAL_BILL) AS "AVERAGE BILL",COUNT(*) AS TOTAL_CUSTOMERS FROM TIPS WHERE SIZE IN (2,3,4) GROUP BY SIZE;

-- FIND THE COUNT OF EACH GROUP SIZE WHOSE COUNT IS MORE THAN 30
SELECT SIZE,COUNT(*) AS "TOTAL CUSTOMERS IN EACH SIZE" FROM TIPS GROUP BY SIZE HAVING COUNT(*) > 30;

-- count the people as per the size and GENDER
SELECT SIZE,GENDER,COUNT(*) AS TOTAL_COUNT FROM TIPS GROUP BY SIZE,GENDER;

-- ORDER BY SIZE
SELECT * FROM TIPS ORDER BY SIZE  ASC;
SELECT * FROM TIPS ORDER BY SIZE DESC;

-- GET THE SIZE MORE THAN 100
SELECT SIZE, COUNT(*) AS TOTAL_SIZE FROM TIPS GROUP BY SIZE HAVING COUNT(*) > 100;
SELECT SIZE,SUM(TOTAL_BILL)AS BILL FROM TIPS GROUP BY SIZE  HAVING SUM(TOTAL_BILL) > 100 ORDER BY BILL DESC;

-- SORT THE RECORD AS TOTAL_BILL DESC ORDER
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC;

-- FIND THE TOPS TOTAL BILL
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC LIMIT 5;

-- FIND THE HIGEST TOTAL_BILL RECORD
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC LIMIT 1;

-- FIND THE SECOND HIGEST TOTAL BILL
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC LIMIT 1 OFFSET 1;

-- FIND THE SECOND AND THIRD  HIGEST TOTAL BILL RECORD
SELECT * FROM TIPS ORDER BY TOTAL_BILL DESC LIMIT 2 OFFSET 1;

-- FIND THE TOP 3 GROUP WHOSE SIZE MORE THAN 30 (IN DESC ORDER AS PER TOTAL COUNT
SELECT SIZE, COUNT(*) AS TOTAL_COUNT
FROM TIPS
GROUP BY SIZE
HAVING COUNT(*) > 30
ORDER BY TOTAL_COUNT DESC
LIMIT 3 OFFSET 1;

